#include "isog.h"
#include "ec.h"
#include <assert.h>

// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------

// Degree-2 isogeny evaluation with kenerl generated by P != (0, 0)
void
xeval_2(ec_point_t *R, ec_point_t *const Q, const int lenQ, const ec_kps2_t *kps)
{
    field_t t0, t1, t2;
    for (int j = 0; j < lenQ; j++) {
        field_add(&t0, &Q[j].x, &Q[j].z);
        field_sub(&t1, &Q[j].x, &Q[j].z);
        field_mul(&t2, &kps->K.x, &t1);
        field_mul(&t1, &kps->K.z, &t0);
        field_add(&t0, &t2, &t1);
        field_sub(&t1, &t2, &t1);
        field_mul(&R[j].x, &Q[j].x, &t0);
        field_mul(&R[j].z, &Q[j].z, &t1);
    }
}

void
xeval_2_singular(ec_point_t *R, const ec_point_t *Q, const int lenQ, const ec_kps2_t *kps)
{
    field_t t0, t1;
    for (int i = 0; i < lenQ; i++) {
        field_mul(&t0, &Q[i].x, &Q[i].z);
        field_mul(&t1, &kps->K.x, &Q[i].z);
        field_add(&t1, &t1, &Q[i].x);
        field_mul(&t1, &t1, &Q[i].x);
        field_sqr(&R[i].x, &Q[i].z);
        field_add(&R[i].x, &R[i].x, &t1);
        field_mul(&R[i].z, &t0, &kps->K.z);
    }
}

// Degree-4 isogeny evaluation with kenerl generated by P such that [2]P != (0, 0)
void
xeval_4(ec_point_t *R, const ec_point_t *Q, const int lenQ, const ec_kps4_t *kps)
{
    const ec_point_t *K = kps->K;

    field_t t0, t1;

    for (int i = 0; i < lenQ; i++) {
        field_add(&t0, &Q[i].x, &Q[i].z);
        field_sub(&t1, &Q[i].x, &Q[i].z);
        field_mul(&(R[i].x), &t0, &K[1].x);
        field_mul(&(R[i].z), &t1, &K[2].x);
        field_mul(&t0, &t0, &t1);
        field_mul(&t0, &t0, &K[0].x);
        field_add(&t1, &(R[i].x), &(R[i].z));
        field_sub(&(R[i].z), &(R[i].x), &(R[i].z));
        field_sqr(&t1, &t1);
        field_sqr(&(R[i].z), &(R[i].z));
        field_add(&(R[i].x), &t0, &t1);
        field_sub(&t0, &t0, &(R[i].z));
        field_mul(&(R[i].x), &(R[i].x), &t1);
        field_mul(&(R[i].z), &(R[i].z), &t0);
    }
}
