#include "isog.h"
#include "ec.h"
#include <assert.h>

// -------------------------------------------------------------------------
// -------------------------------------------------------------------------

// Degree-2 isogeny with kernel generated by P != (0 ,0)
// Outputs the curve coefficient in the form A24=(A+2C:4C)
void
xisog_2(ec_kps2_t *kps, ec_point_t *B, const ec_point_t P)
{
    field_sqr(&B->x, &P.x);
    field_sqr(&B->z, &P.z);
    field_sub(&B->x, &B->z, &B->x);
    field_add(&kps->K.x, &P.x, &P.z);
    field_sub(&kps->K.z, &P.x, &P.z);
}

void
xisog_2_singular(ec_kps2_t *kps, ec_point_t *B24, ec_point_t A24)
{
    // No need to check the square root, only used for signing.
    field_t t0, four;
    field_set_small(&four, 4);
    field_add(&t0, &A24.x, &A24.x);
    field_sub(&t0, &t0, &A24.z);
    field_add(&t0, &t0, &t0);
    field_inv(&A24.z);
    field_mul(&t0, &t0, &A24.z);
    field_copy(&kps->K.x, &t0);
    field_add(&B24->x, &t0, &t0);
    field_sqr(&t0, &t0);
    field_sub(&t0, &t0, &four);
    field_sqrt(&t0);
    field_neg(&kps->K.z, &t0);
    field_add(&B24->z, &t0, &t0);
    field_add(&B24->x, &B24->x, &B24->z);
    field_add(&B24->z, &B24->z, &B24->z);
}

// Degree-4 isogeny with kernel generated by P such that [2]P != (0 ,0)
// Outputs the curve coefficient in the form A24=(A+2C:4C)
void
xisog_4(ec_kps4_t *kps, ec_point_t *B, const ec_point_t P)
{
    ec_point_t *K = kps->K;

    field_sqr(&K[0].x, &P.x);
    field_sqr(&K[0].z, &P.z);
    field_add(&K[1].x, &K[0].z, &K[0].x);
    field_sub(&K[1].z, &K[0].z, &K[0].x);
    field_mul(&B->x, &K[1].x, &K[1].z);
    field_sqr(&B->z, &K[0].z);

    // Constants for xeval_4
    field_add(&K[2].x, &P.x, &P.z);
    field_sub(&K[1].x, &P.x, &P.z);
    field_add(&K[0].x, &K[0].z, &K[0].z);
    field_add(&K[0].x, &K[0].x, &K[0].x);
}

// 3-isogeny with kernel generated by P. Optimized formulas found in https://eprint.iacr.org/2017/504.pdf (Appendix A)
void 
xisog_3(ec_kps_t *kps, ec_point_t *B24, const ec_point_t P)
{
    ec_point_t K;
    field_t r1, r2, r3, r4, r5;

    field_sub(&K.x,&P.x,&P.z);
    field_add(&K.z,&P.x,&P.z);

    kps->K=(ec_point_t *)malloc(sizeof(ec_point_t));
    kps->K[0]=K;

    field_sqr(&r1,&K.x); // r1=K1^2 ((x-z)^2)
    field_sqr(&r2,&K.z); // r2=K2^2 ((x+z)^2)
    field_add(&r3,&r1,&r2); //r3=r1+r2 ((x-z)^2+(x+z)^2=2(x^2+z^2))
    field_add(&r4,&K.x,&K.z); // r4=K1+K2 (2x)
    field_sqr(&r4,&r4); // r4=r4^2 (4x^2)
    field_sub(&r4,&r4,&r3); // r4=r4-r3 (2(x^2-z^2))
    field_add(&r3,&r4,&r2); // r3=r4+r2 ((x+z)(3x-z))
    field_add(&r4,&r4,&r1); // r4=r4+r1 ((x-z)(3x+z))
    field_add(&r5,&r1,&r4); // r5=r1+r4 (4x(x-z))
    field_add(&r5,&r5,&r5); // r5=2r5 (8x(x-z))
    field_add(&r5,&r5,&r2); // r5=r5+r2 (8x(x-z)+(x+z)^2=9x^2-6xz+z^2=(3x-z)^2)
    field_mul(&B24->x,&r3,&r5); // A24=r3.r5=(x+z)(3x-z)^3
    field_add(&r5,&r2,&r3); // r5=r2+r3 (4x(x+z))
    field_add(&r5,&r5,&r5); // r5=2r5 (8x(x+z))
    field_add(&r5,&r5,&r1); // r5=r5+r1 (8x(x+z)+(x-z)^2=9x^2+6xz+z^2=(3x+z)^2)
    field_mul(&r5,&r5,&r4); // r5=r5.r4 ((x-z)(3x+z)^3)
    field_sub(&B24->z,&r5,&B24->x); // C24=r5-A24=-16xz^3. 
    field_add(&B24->x,&B24->x,&B24->z); // (A-2C:4C) -> (A+2C:4C). OK
}

// (2d+1)-isogeny with kernel generated by P. Optimized formulas found in https://eprint.iacr.org/2017/504.pdf (Algorithm 2)
void
xisog_odd(ec_kps_t *kps, ec_point_t *B24, const ec_point_t P, const ec_point_t *A24, ec_point_t P2, unsigned int d)
{
    // P2 is a 2-torsion point !=(0,0) used to recover the codomain B24
    ec_point_t kpsK[d], Q2;

    copy_point(&kpsK[0],&P);
    xDBL_A24(&kpsK[1],&P,A24);
    for(int i=2; i<d;i++){
        xADD(&kpsK[i],&kpsK[i-1],&P,&kpsK[i-2]);
    }

    kps->K=(ec_point_t *)malloc(d*sizeof(ec_point_t));
    for(int i=0;i<d;i++){
        kps->K[i]=kpsK[i];
    }

    xeval_odd(&Q2, &P2, 1, kps, d);
    field_add(&B24->x,&Q2.x,&Q2.z); // x+z
    field_sqr(&B24->x,&B24->x); // (x+z)^2
    field_sub(&B24->z,&Q2.x,&Q2.z); // x-z
    field_sqr(&B24->z,&B24->z); // (x-z)^2
    field_sub(&B24->z,&B24->z,&B24->x); // (x-z)^2-(x+z)^2
}